# Generated by Django 6.0.4 on 2026-04-20 14:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('INITIAL', 'Initial Authorization'), ('RENEWAL', 'Renewal / Continuation'), ('EMERGENCY', 'Emergency Authorization'), ('APPEAL', 'Appeal')], default='INITIAL', max_length=20)),
                ('submitter_name', models.CharField(blank=True, max_length=200)),
                ('submitter_notes', models.TextField(blank=True, help_text='Additional context from submitter')),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('STAT', 'STAT/Emergency')], default='ROUTINE', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/')),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('ocr_confidence', models.FloatField(default=0.0)),
                ('document_count', models.IntegerField(default=1)),
                ('disease', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('patient_info', models.TextField(blank=True)),
                ('icd_codes', models.TextField(blank=True)),
                ('cpt_codes', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('procedures', models.TextField(blank=True)),
                ('lab_values', models.JSONField(blank=True, default=dict)),
                ('vitals', models.JSONField(blank=True, default=dict)),
                ('allergies', models.TextField(blank=True)),
                ('dosage_info', models.TextField(blank=True)),
                ('decision', models.CharField(choices=[('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('PENDING', 'Pending Review'), ('INSUFFICIENT', 'Insufficient Data'), ('PARTIAL', 'Partial Approval')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('rule_flags', models.JSONField(blank=True, default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(blank=True, max_length=10)),
                ('completeness_score', models.FloatField(default=0.0, help_text='0-100 document completeness')),
                ('ai_explanation', models.TextField(blank=True)),
                ('ai_suggestions', models.TextField(blank=True)),
                ('appeal_letter', models.TextField(blank=True)),
                ('clinical_summary', models.TextField(blank=True)),
                ('missing_fields', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('ERROR', 'Error')], default='PROCESSING', max_length=20)),
                ('processing_time_ms', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Authorization Request',
                'verbose_name_plural': 'Authorization Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('payer', models.CharField(blank=True, max_length=200)),
                ('policy_code', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('requires_step_therapy', models.BooleanField(default=False)),
                ('requires_prior_auth', models.BooleanField(default=True)),
                ('max_days_supply', models.IntegerField(default=30)),
                ('covered_diagnoses', models.TextField(blank=True)),
                ('excluded_treatments', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('UPLOAD', 'Document Upload'), ('OCR', 'OCR Extraction'), ('NLP', 'NLP Analysis'), ('RULES', 'Rule Evaluation'), ('ML', 'ML Prediction'), ('LLM', 'LLM Reasoning'), ('OUTPUT', 'Output Generated')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='extract.authorizationrequest')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=20)),
                ('file_size', models.IntegerField(default=0)),
                ('page_count', models.IntegerField(default=1)),
                ('extracted_text', models.TextField(blank=True)),
                ('ocr_confidence', models.FloatField(default=0.0)),
                ('document_label', models.CharField(blank=True, help_text="e.g. 'Prescription', 'Lab Report', 'Referral Letter'", max_length=100)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='extract.authorizationrequest')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
