# Generated by Django 6.0.4 on 2026-04-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationrequest',
            name='fraud_risk',
            field=models.CharField(default='LOW', max_length=10),
        ),
        migrations.AddField(
            model_name='authorizationrequest',
            name='validation_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='authorizationrequest',
            name='validation_score',
            field=models.FloatField(default=1.0),
        ),
    ]
