# Generated by Django 6.0.4 on 2026-04-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0002_authorizationrequest_fraud_risk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationrequest',
            name='consistency_level',
            field=models.CharField(default='LOW', max_length=10),
        ),
    ]
