# Generated by Django 6.0.4 on 2026-04-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0003_authorizationrequest_consistency_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationrequest',
            name='ai_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='authorizationrequest',
            name='ai_appeal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='authorizationrequest',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
    ]
